

name: Pod Info

steps:
- id: auth
  uses: google-github-actions/auth@v0.4.0
  with:
    workload_identity_provider: projects/299817019527/locations/global/workloadIdentityPools/github-action/providers/github-action
    service_account: github-action-wif@proserv-task01.iam.gserviceaccount.com

- id: get-gke-credentials
  uses: google-github-actions/get-gke-credentials@v0.4.0
  with:
    cluster_name: my-tf-cluster
    location: us-central1-a

- id: get-pods
  run: kubectl get pods
